apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-update-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100M
  storageClassName: standard